---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Docker Compose
      command: docker-compose up -d 
      args:
        chdir: /var/lib/jenkins/workspace/WeatherWise/devops
