version: "3.3"

services:
  
  backend:
    image: 48483/weatherwisebackend:latest
    ports:
      - "8082:8082"
    networks:
      - wise
    environment:
      DB_URL: jdbc:mysql://db:3306/weatherwise?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: Rishabh@1234
      LOGS_FILE: /logs/app.log
    depends_on:
      - db
    volumes:
      - /home/weatherwise/logs:/logs

  db:
    image: mysql:latest
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: Rishabh@1234
      MYSQL_DATABASE: weatherwise
    networks:
      - wise
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - database-volume:/var/lib/mysql
  
  frontend:
    image: 48483/weatherwisefrontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wise

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - elk

volumes:
  database-volume:
  elastic_data: {}

networks:
  wise:
  elk:
