---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get Docker image facts
      docker_image_facts:

    - name: Get list of running containers
      command: docker ps -q
      register: running_containers

    - name: Remove Docker images not tagged as "latest" and their containers
      block:
        - name: Loop through each image and remove it if not tagged as "latest"
          command: docker image rm "{{ item }}"
          loop: "{{ ansible_facts.docker_images }}"
          when: "'latest' not in item.tags"

        - name: Stop and remove containers corresponding to removed images
          command: docker rm -f "{{ item }}"
          loop: "{{ running_containers.stdout_lines }}"
          when: "item.split(':')[0] not in ansible_facts.docker_images|map(attribute='repository')|list"
          
    - name: Remoce orphans for Application
      command: docker-compose down --remove-orphans
      args:
        chdir: /var/lib/jenkins/workspace/WeatherWise/devops
      register: docker_cleanup_result

    - name: Remoce orphans for ELK
      command: docker-compose down --remove-orphans
      args:
        chdir: /var/lib/jenkins/workspace/WeatherWise/devops/elk-docker-compose
      register: docker_cleanup_result

    - name: Run Docker Compose For Application
      command: docker-compose up -d
      args:
        chdir: /var/lib/jenkins/workspace/WeatherWise/devops

    - name: Run Docker Compose For ELK
      command: docker-compose up -d
      args:
        chdir: /var/lib/jenkins/workspace/WeatherWise/devops/elk-docker-compose
