filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ../backend/Springboot-ELK.log
  fields:
    log_type: flask_app_log

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]